apiVersion: v1
kind: Service
metadata:
  name: juice-shop
  labels:
    app: juice-shop
spec:
  type: NodePort
  selector:
    app: juice-shop
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
